;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.0
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(cl:in-package :cl-user)

(defpackage #:vrpn
  (:use #:cl #:cffi)
  (:shadow #:char #:float #:byte #:boolean #:string)
  (:export
        vrpn-base-class-unique
        vrpn-base-class
        mainloop
        vrpn-analog
        vrpn-analog-remote
        register-change-handler
        unregister-change-handler
        vrpn-button
        vrpn-button-remote
        vrpn-tracker
        vrpn-tracker-remote ))