;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.0
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(defsystem vrpn
  :depends-on (cffi)
  :components ((:file "vrpn-package")
               (:file "vrpn-library" :depends-on ("vrpn-package"))
               (:file "vrpn" :depends-on ("vrpn-library"))
               (:file "vrpn-clos" :depends-on ("vrpn"))))
